### ISSUE TITLE
Move topo-descriptor under the MeteoSwiss account on pypi

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/topo-descriptors#4]
Hey @dnerini and @matschaer, 

I'd like to suggest to move the existing pypi releases of topo-descriptor under the pypi account [MeteoSwiss](https://pypi.org/user/MeteoSwiss/). 

To do so requires @dnerini to login onto pypi, and under the package page add "MeteoSwiss" as owner. 

To ease the CI/CD, I could suggest the addition of [this action](https://github.com/MeteoSwiss/ampycloud/blob/develop/.github/workflows/CI_pypi.yml) to your Github repo.

What do you think ? If this works out smoothly, I'd try to do the same for all other public MCH codes on pypi.

**Comment by dnerini** [comment]
Thanks @fpavogt for the nice suggestions! I just sent an invitation to user "MeteoSwiss" to join the "topo-descriptors" project as owner.

I will also update our GitHub Actions as you suggest.

**Comment by fpavogt** [comment]
Hey @dnerini, it worked ! "MeteoSwiss" is now an owner of topo-descriptors on pypi. If that is ok for you, I'll set your role as "maintainer" on there. You'll still be able to push new releases using your credentials, but won't be able to delete anything (only "MeteoSwiss" would be able to do that). What do you think ?

For the Github action, I just remembered that you had something similar already setup. The main difference would be to use the organization-wide secrets ``PYPI_API_TOKEN`` and ``TESTPYPI_API_TOKEN`` to do the authentication.

**Comment by dnerini** [comment]
> For the Github action, I just remembered that you had something similar already setup. The main difference would be to use the organization-wide secrets `PYPI_API_TOKEN` and `TESTPYPI_API_TOKEN` to do the authentication.

Done in [371b604](https://github.com/MeteoSwiss/topo-descriptors/commit/371b60474c95495959fc2a7cb61fdd671dcef449).
